export const modelSamples = {
  YourCompanies: {
    id: 0,
    name: '',
    logo: '',
    address: '',
    phone: '',
    contact: '',
    createdAt: '',
    updatedAt: '',
  },
  Clients: {
    id: 0,
    name: 'Company Name',
    address: 'Company Address',
    phone: 'Company Phone',
    contact: 'Full Name',
    createdAt: '',
    updatedAt: '',
  },
  Invoices: {
    id: 0,
    type: "Invoice",
    currency: "USD",
    issueDate: "",
    dueDate: "",
    notes: "",
    paymentDetails: "",
    tax: 0,
    from: "",
    to: "",
    items: [],
    createdAt: "",
    updatedAt: "",
    accountId: 0,
    clientsId: 0,
  }
};
